- name: Copying over a sample PVC file for NFS
  template:
    src: templates/registry-pvc.yaml.j2
    dest: "{{ registry_pvc_location }}"
    owner: root
    group: root
    mode: 0666

- name: login as super user with token on OpenShift 4
  shell: "/usr/local/bin/oc login --token={{ openshift_token }}  --server={{ openshift_url }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
  when:
   - openshift_token is defined
   - openshift_token is not none
   - openshift_token|trim() | length > 0
   - openshift_version == "ocp4"
  ignore_errors: no


- name: login as super user with token on OpenShift 3
  shell: "/usr/local/bin/oc login {{ openshift_url }} --token={{ openshift_token }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
  when:
   - openshift_token is defined
   - openshift_token is not none
   - openshift_token|trim() | length > 0
   - openshift_version == "ocp3"
  ignore_errors: no

- name: Switch to project for openshift-image-registry
  command:  "/usr/local/bin/oc project openshift-image-registry"
  register: switch_project_result

- name: Change ManagementState Image Registry Operator configuration from Removed to Managed.
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"managementState\": \"Managed\"}}'"
  when: not delete_deployment|bool


- name: Create persistent volume for registry
  command: "/usr/local/bin/oc create -f {{ registry_pvc_location }}"
  register: pvc_loc_result
  when: not delete_deployment|bool

- name: Configuring registry storage
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"storage\": {\"pvc\": {\"claim\": \"image-registry-pvc\"}}}}'"
  when: not delete_deployment|bool

- debug:
    msg: Run the Following Command /usr/local/bin/oc get co to check clusteroperator status of registry.
  when: not delete_deployment|bool

- name: Change ManagementState Image Registry Operator configuration from Managed to Removed.
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"managementState\": \"Removed\"}}'"
  register: storage_class_result
  ignore_errors: yes
  when: delete_deployment|bool

- name: "Check that the {{ registry_pvc_location }} exists"
  stat:
    path: "{{ registry_pvc_location }}"
  register: registry_pvc_result

- name: Delete persistent volume for registry
  command: "/usr/local/bin/oc delete -f {{ registry_pvc_location }}"
  ignore_errors: yes
  when: delete_deployment|bool and  registry_pvc_result.stat.exists|bool

- name: Remove stoage pvc entry from configs.imageregistry.operator.openshift.io
  shell: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type json  -p '[{ \"op\": \"remove\", \"path\": \"/spec/storage/pvc\" }]'"
  ignore_errors: yes
  when: delete_deployment|bool

- name: Get PV name
  shell: |
    /usr/local/bin/oc get pv -n openshift-image-registry | grep nfs-storage-provisioner | awk '{print $1}'
  ignore_errors: yes
  register: pv_removal_name
  when: delete_deployment|bool


- name: Remove pv from cluster
  command: "/usr/local/bin/oc delete pv {{ pv_removal_name.stdout }} -n openshift-image-registry"
  ignore_errors: yes
  when: delete_deployment|bool and  pv_removal_name.stdout | length > 0
