- name: Copying over a sample PVC file for NFS
  template:
    src: templates/registry-pvc.yaml.j2
    dest: "{{ registry_pvc_location }}"
    owner: root
    group: root
    mode: 0666

- name: Switch to project for openshift-image-registry
  command:  "/usr/local/bin/oc project openshift-image-registry"
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  register: switch_project_result

- name: Change ManagementState Image Registry Operator configuration from Removed to Managed.
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"managementState\": \"Managed\"}}'"
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: not delete_deployment


- name: Create persistent volume for registry
  command: "/usr/local/bin/oc create -f {{ registry_pvc_location }}"
  register: pvc_loc_result
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: not delete_deployment

- name: Configuring registry storage
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"storage\": {\"pvc\": {\"claim\": \"image-registry-pvc\"}}}}'"
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: not delete_deployment

- debug:
    msg: Run the Following Command /usr/local/bin/oc get co to check clusteroperator status of registry.
  when: not delete_deployment

- name: Delete persistent volume for registry
  command: "/usr/local/bin/oc delete -f {{ registry_pvc_location }}"
  register: pvc_loc_result
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: delete_deployment

- name: Change ManagementState Image Registry Operator configuration from Managed to Removed.
  command: "/usr/local/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"managementState\": \"Removed\"}}'"
  register: storage_class_result
  environment:
   KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: delete_deployment
